### ISSUE TITLE
txt2text not working

### ISSUE THREAD

**Issue by andre-macdonald** [artitw/text2text#17]
I have a save copy of t2t but now it doesn't work anymore. Please help?

**Comment by andre-macdonald** [comment]
> Sorry to hear this. What steps did you try? Have you gotten the Colab notebook example to work?

I have been able to get it working even after deleting and reuploading
![t2t error](https://user-images.githubusercontent.com/80366116/114999873-16651a00-9e57-11eb-8ae7-123b82873456.png)

**Comment by artitw** [comment]
Thanks for bringing this up and providing your results. Some imports have been fixed and a new package published. Can you re-run the notebook and report back if it works?

**Comment by andre-macdonald** [comment]
Working. Thank you so much
