### ISSUE TITLE
expected scalar type Half but found Float error in generating question

### ISSUE THREAD

**Issue by sougata-fiz** [artitw/text2text#3]
Hi,
I am getting `RuntimeError: expected scalar type Half but found Float` while using `output_type="question"`. Any leads on how to fix this?

Thanks

**Comment by sougata-fiz** [comment]
Full error
`RuntimeError: expected scalar type Half but found Float (data_ptr<c10::Half> at /usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorMethods.h:6321)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7efdd3f54193 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: c10::Half* at::Tensor::data_ptr<c10::Half>() const + 0x44c (0x7efda139912c in /usr/local/lib/python3.6/dist-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #2: cuda_layer_norm(at::Tensor*, at::Tensor*, at::Tensor*, at::Tensor*, int, int, c10::ArrayRef<long>, at::Tensor*, at::Tensor*, double) + 0x2f1 (0x7efda1394271 in /usr/local/lib/python3.6/dist-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #3: layer_norm_affine(at::Tensor, c10::ArrayRef<long>, at::Tensor, at::Tensor, double) + 0x2b3 (0x7efda137d673 in /usr/local/lib/python3.6/dist-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x22fe5 (0x7efda1392fe5 in /usr/local/lib/python3.6/dist-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x1e010 (0x7efda138e010 in /usr/local/lib/python3.6/dist-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #6: /usr/bin/python3() [0x50ac25]
frame #7: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #8: /usr/bin/python3() [0x508245]
frame #9: /usr/bin/python3() [0x5893bb]
frame #10: PyObject_Call + 0x3e (0x5a067e in /usr/bin/python3)
frame #11: THPFunction_apply(_object*, _object*) + 0xa8f (0x7efe1efae82f in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #12: /usr/bin/python3() [0x50a8af]
frame #13: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #14: _PyFunction_FastCallDict + 0xf5 (0x509455 in /usr/bin/python3)
frame #15: /usr/bin/python3() [0x595311]
frame #16: PyObject_Call + 0x3e (0x5a067e in /usr/bin/python3)
frame #17: _PyEval_EvalFrameDefault + 0x17f6 (0x50d966 in /usr/bin/python3)
frame #18: /usr/bin/python3() [0x508245]
frame #19: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #20: /usr/bin/python3() [0x595311]
frame #21: /usr/bin/python3() [0x54b1e1]
frame #22: _PyObject_FastCallKeywords + 0x19c (0x5aa6ec in /usr/bin/python3)
frame #23: /usr/bin/python3() [0x50abb3]
frame #24: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #25: _PyFunction_FastCallDict + 0xf5 (0x509455 in /usr/bin/python3)
frame #26: /usr/bin/python3() [0x595311]
frame #27: PyObject_Call + 0x3e (0x5a067e in /usr/bin/python3)
frame #28: _PyEval_EvalFrameDefault + 0x17f6 (0x50d966 in /usr/bin/python3)
frame #29: /usr/bin/python3() [0x508245]
frame #30: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #31: /usr/bin/python3() [0x595311]
frame #32: /usr/bin/python3() [0x54b1e1]
frame #33: _PyObject_FastCallKeywords + 0x19c (0x5aa6ec in /usr/bin/python3)
frame #34: /usr/bin/python3() [0x50abb3]
frame #35: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #36: /usr/bin/python3() [0x508245]
frame #37: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #38: /usr/bin/python3() [0x595311]
frame #39: PyObject_Call + 0x3e (0x5a067e in /usr/bin/python3)
frame #40: _PyEval_EvalFrameDefault + 0x17f6 (0x50d966 in /usr/bin/python3)
frame #41: /usr/bin/python3() [0x508245]
frame #42: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #43: /usr/bin/python3() [0x595311]
frame #44: /usr/bin/python3() [0x54b1e1]
frame #45: _PyObject_FastCallKeywords + 0x19c (0x5aa6ec in /usr/bin/python3)
frame #46: /usr/bin/python3() [0x50abb3]
frame #47: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #48: /usr/bin/python3() [0x508245]
frame #49: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #50: /usr/bin/python3() [0x595311]
frame #51: PyObject_Call + 0x3e (0x5a067e in /usr/bin/python3)
frame #52: _PyEval_EvalFrameDefault + 0x17f6 (0x50d966 in /usr/bin/python3)
frame #53: /usr/bin/python3() [0x508245]
frame #54: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #55: /usr/bin/python3() [0x595311]
frame #56: /usr/bin/python3() [0x54b1e1]
frame #57: _PyObject_FastCallKeywords + 0x19c (0x5aa6ec in /usr/bin/python3)
frame #58: /usr/bin/python3() [0x50abb3]
frame #59: _PyEval_EvalFrameDefault + 0x1220 (0x50d390 in /usr/bin/python3)
frame #60: /usr/bin/python3() [0x508245]
frame #61: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #62: /usr/bin/python3() [0x595311]
frame #63: PyObject_Call + 0x3e (0x5a067e in /usr/bin/python3)`

**Comment by artitw** [comment]
It might help if you describe your setup. Have you run the demo on colab? https://colab.research.google.com/drive/1LE_ifTpOGO5QJCKNQYtZe6c_tjbwnulR

**Comment by sougata-fiz** [comment]
I have run the Colab demo notebook. The problem arises when I run the question generation code, followed by summary, followed by question generation. Below is a demo of the same.
`from text2text.text_generator import TextGenerator
qg = TextGenerator(output_type="question")

bio_str = "Biology is the science that studies life. What exactly is life? This may sound like a silly question with an obvious answer, but it is not easy to define life. For example, a branch of biology called virology studies viruses, which exhibit some of the characteristics of living entities but lack others. It turns out that although viruses can attack living organisms, cause diseases, and even reproduce, they do not meet the criteria that biologists use to define life."

`qg.predict([bio_str,
            bio_str])` 

```
***** Recover model: %s ***** qg_model.bin
100%|██████████| 1/1 [00:01<00:00,  1.70s/it]
[('What is biology the science that studies?', 'life'),
 ('What is the study of life?', 'studies')]
```
`sg = TextGenerator(output_type="summary")
sg.predict([bio_str])`

```
enable fp16 with amp
***** Recover model: %s ***** cnndm_model.bin
100%|██████████| 1/1 [00:07<00:00,  7.95s/it]
['biology is the science that studies life .']
```

`qg.predict([bio_str])`
This is where I get the error.
`RuntimeError: expected scalar type Half but found Float (data_ptr<c10::Half> at /usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorMethods.h:6321)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7eff31b3d193 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: c10::Half* at::Tensor::data_ptr<c10::Half>() const + 0x44c (0x7eff1ceb912c in /usr/local/lib/python3.6/dist-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #2: cuda_layer_norm(at::Tensor*, at::Tensor*, at::Tensor*, at::Tensor*, int, int, c10::ArrayRef<long>, at::Tensor*, at::Tensor*, double) + 0x2f1 (0x7eff1ceb4271 in /usr/local/lib/python3.6/dist-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #3: layer_norm_affine(at::Tensor, c10::ArrayRef<long>, at::Tensor, at::Tensor, double) + 0x2b3 (0x7eff1ce9d673 in /usr/local/lib/python3.6/dist-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x22fe5 (0x7eff1ceb2fe5 in /usr/local/lib/python3.6/dist-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x1e010 (0x7eff1ceae010 in /usr/local/lib/python3.6/dist-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #6: /usr/bin/python3() [0x50ac25]
frame #7: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #8: /usr/bin/python3() [0x508245]
frame #9: /usr/bin/python3() [0x5893bb]
frame #10: PyObject_Call + 0x3e (0x5a067e in /usr/bin/python3)
frame #11: THPFunction_apply(_object*, _object*) + 0xa8f (0x7eff7cb9782f in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #12: /usr/bin/python3() [0x50a8af]
frame #13: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #14: _PyFunction_FastCallDict + 0xf5 (0x509455 in /usr/bin/python3)
frame #15: /usr/bin/python3() [0x595311]
frame #16: PyObject_Call + 0x3e (0x5a067e in /usr/bin/python3)
frame #17: _PyEval_EvalFrameDefault + 0x17f6 (0x50d966 in /usr/bin/python3)
frame #18: /usr/bin/python3() [0x508245]
frame #19: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #20: /usr/bin/python3() [0x595311]
frame #21: /usr/bin/python3() [0x54b1e1]
frame #22: _PyObject_FastCallKeywords + 0x19c (0x5aa6ec in /usr/bin/python3)
frame #23: /usr/bin/python3() [0x50abb3]
frame #24: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #25: _PyFunction_FastCallDict + 0xf5 (0x509455 in /usr/bin/python3)
frame #26: /usr/bin/python3() [0x595311]
frame #27: PyObject_Call + 0x3e (0x5a067e in /usr/bin/python3)
frame #28: _PyEval_EvalFrameDefault + 0x17f6 (0x50d966 in /usr/bin/python3)
frame #29: /usr/bin/python3() [0x508245]
frame #30: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #31: /usr/bin/python3() [0x595311]
frame #32: /usr/bin/python3() [0x54b1e1]
frame #33: _PyObject_FastCallKeywords + 0x19c (0x5aa6ec in /usr/bin/python3)
frame #34: /usr/bin/python3() [0x50abb3]
frame #35: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #36: /usr/bin/python3() [0x508245]
frame #37: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #38: /usr/bin/python3() [0x595311]
frame #39: PyObject_Call + 0x3e (0x5a067e in /usr/bin/python3)
frame #40: _PyEval_EvalFrameDefault + 0x17f6 (0x50d966 in /usr/bin/python3)
frame #41: /usr/bin/python3() [0x508245]
frame #42: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #43: /usr/bin/python3() [0x595311]
frame #44: /usr/bin/python3() [0x54b1e1]
frame #45: _PyObject_FastCallKeywords + 0x19c (0x5aa6ec in /usr/bin/python3)
frame #46: /usr/bin/python3() [0x50abb3]
frame #47: _PyEval_EvalFrameDefault + 0x449 (0x50c5b9 in /usr/bin/python3)
frame #48: /usr/bin/python3() [0x508245]
frame #49: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #50: /usr/bin/python3() [0x595311]
frame #51: PyObject_Call + 0x3e (0x5a067e in /usr/bin/python3)
frame #52: _PyEval_EvalFrameDefault + 0x17f6 (0x50d966 in /usr/bin/python3)
frame #53: /usr/bin/python3() [0x508245]
frame #54: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #55: /usr/bin/python3() [0x595311]
frame #56: /usr/bin/python3() [0x54b1e1]
frame #57: _PyObject_FastCallKeywords + 0x19c (0x5aa6ec in /usr/bin/python3)
frame #58: /usr/bin/python3() [0x50abb3]
frame #59: _PyEval_EvalFrameDefault + 0x1220 (0x50d390 in /usr/bin/python3)
frame #60: /usr/bin/python3() [0x508245]
frame #61: _PyFunction_FastCallDict + 0x2e2 (0x509642 in /usr/bin/python3)
frame #62: /usr/bin/python3() [0x595311]
frame #63: PyObject_Call + 0x3e (0x5a067e in /usr/bin/python3)`

**Comment by artitw** [comment]
Just cleaned up some dependencies. Try it again and let us know if you run into other issues.

**Comment by sougata-fiz** [comment]
This works fine now. Closing this issue. Thanks!
