### ISSUE TITLE
Assostant colab fails

### ISSUE THREAD

**Issue by mariannadeganutti** [artitw/text2text#43]
I tried the Assistant Colab notebook and it fails while running the second cell, asst = t2t.Assistant().

I got the following error. Perhaps there is some issue with out of date dependencies, is it possible to fix?

```
GatedRepoError: 401 Client Error. (Request ID: Root=1-669ec1dc-5784c5d67d31829f5e975ec7;3201d19d-1677-421c-b769-957fbf2c4286)

Cannot access gated repo for url https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1/resolve/main/config.json.
Access to model mistralai/Mixtral-8x7B-Instruct-v0.1 is restricted. You must be authenticated to access it.
```

![Screenshot from 2024-07-22 22-34-55](https://github.com/user-attachments/assets/ce67d0bc-b9e3-4ad8-aaf8-6407b56a387b)

**Comment by artitw** [comment]
Thanks for reporting this. It should be fixed now. Can you try re-running it again and report back if it still has problems?

**Comment by mariannadeganutti** [comment]
Thank you, it works now. I'm now getting
`llama3.1 is not loading up. Maybe needs more memory. Restarting and trying again might help.`
but I guess that's not a problem with the code

**Comment by artitw** [comment]
If you are on Colab try restarting to clear memory. If it does not resolve please report back

**Comment by mariannadeganutti** [comment]
The default T4 runtime gives the same issue, TPU v2 fails at pip install (error: uninstall-distutils-installed-package .. etc), but CPU works. Thank you!

**Comment by artitw** [comment]
It works for me on T4, which should be faster than CPU
